### ISSUE TITLE
[Bug] Game crashes when enchanting/reforging

### ISSUE THREAD

**Issue by DaniDamu** [BiscuitDevelopment/SkyblockAddons#364]
Please note that we do not provide support for clients other than Forge.
We will not fix compatibility issues with other clients.

**Describe the bug**
when i enchant or reforge an item my Minecraft crashes
**To Reproduce**
Steps to reproduce the behavior (how did you get this bug to occur):
1. Go to my enchanting table  'or the blacksmith
2. Click on 'any enchant or click the anvil to reforge'
3. See error

**video of the bug**
https://youtu.be/CI_s3dUFJIU

**Crash Report**
If your game crashed, please paste the beginning of your crash report here. Copy from the beginning until the line shown below.
> A detailed walkthrough of the error, its code path and all known details is as follows:--- Minecraft Crash Report ----

WARNING: coremods are present:
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.8.9-1.5.2.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 8/17/20 3:37 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:241)
	at net.minecraft.client.renderer.ItemModelMesher.func_178084_b(ItemModelMesher.java:77)
	at net.minecraft.client.renderer.ItemModelMesher.func_178089_a(ItemModelMesher.java:42)
	at net.minecraft.client.renderer.entity.RenderItem.func_175042_a(RenderItem.java:508)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.renderItem(RenderListener.java:1180)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.drawText(RenderListener.java:871)
	at codes.biscuit.skyblockaddons.core.Feature.draw(Feature.java:236)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.renderOverlays(RenderListener.java:296)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.onRenderRegular(RenderListener.java:99)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_25_RenderListener_onRenderRegular_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:851)
	at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:558)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:145)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1396)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:241)
	at net.minecraft.client.renderer.ItemModelMesher.func_178084_b(ItemModelMesher.java:77)
	at net.minecraft.client.renderer.ItemModelMesher.func_178089_a(ItemModelMesher.java:42)
	at net.minecraft.client.renderer.entity.RenderItem.func_175042_a(RenderItem.java:508)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.renderItem(RenderListener.java:1180)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.drawText(RenderListener.java:871)
	at codes.biscuit.skyblockaddons.core.Feature.draw(Feature.java:236)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.renderOverlays(RenderListener.java:296)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.onRenderRegular(RenderListener.java:99)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_25_RenderListener_onRenderRegular_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:851)
	at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:558)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:145)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['DaniDamu'/267543, l='MpServer', x=3.30, y=98.00, z=9.30], EntityOtherPlayerMP['Mrendonuts'/2338650, l='MpServer', x=3.28, y=110.31, z=9.28]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 0.00,100.00,0.00 - World: (0,100,0), Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 515 game time, 21460 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 48 total; [EntityArmorStand['§8[§7Lv4§8] §cSpider §a183§f/§a183§c?'/2339680, l='MpServer', x=60.09, y=3.19, z=22.13], EntityArmorStand['§8[§7Lv4§8] §cSkeleton §a152§f/§a152§c?'/2339247, l='MpServer', x=31.50, y=4.00, z=-23.50], EntitySkeleton['Skeleton'/2339246, l='MpServer', x=31.50, y=2.00, z=-23.50], EntityArmorStand['§8[§7Lv4§8] §cZombie §a152§f/§a152§c?'/2339053, l='MpServer', x=32.50, y=4.09, z=-29.50], EntityZombie['Zombie'/2339052, l='MpServer', x=32.50, y=2.00, z=-29.50], EntityArmorStand['§8[§7Lv4§8] §cSkeleton §a152§f/§a152§c?'/2339251, l='MpServer', x=37.50, y=4.00, z=-23.50], EntitySkeleton['Skeleton'/2339250, l='MpServer', x=37.50, y=2.00, z=-23.50], EntityArmorStand['Armor Stand'/2342642, l='MpServer', x=9.50, y=99.84, z=33.50], EntityArmorStand['Armor Stand'/2342641, l='MpServer', x=9.50, y=100.09, z=33.50], EntityArmorStand['Armor Stand'/2342640, l='MpServer', x=9.50, y=100.34, z=33.50], EntityArmorStand['§8[§7Lv4§8] §cSkeleton §a152§f/§a152§c?'/2339511, l='MpServer', x=36.50, y=4.00, z=-37.50], EntitySkeleton['Skeleton'/2339510, l='MpServer', x=36.50, y=2.00, z=-37.50], EntityPig['Pig'/2340472, l='MpServer', x=-2.69, y=100.00, z=-27.53], EntityPlayerSP['DaniDamu'/267543, l='MpServer', x=3.30, y=98.00, z=9.30], EntityArmorStand['§8[§7Lv4§8] §cSkeleton §a152§f/§a152§c?'/2338749, l='MpServer', x=36.50, y=4.00, z=13.50], EntitySkeleton['Skeleton'/2338748, l='MpServer', x=36.50, y=2.00, z=13.50], EntityVillager['Villager'/2338562, l='MpServer', x=9.50, y=100.00, z=33.50], EntityCow['Cow'/2342146, l='MpServer', x=-3.69, y=100.00, z=-18.63], EntityArmorStand['Armor Stand'/2338567, l='MpServer', x=3.50, y=101.00, z=4.50], EntityArmorStand['Armor Stand'/2338823, l='MpServer', x=3.50, y=94.03, z=-17.50], EntityArmorStand['§8[§7Lv4§8] §cZombie §a152§f/§a152§c?'/2339655, l='MpServer', x=57.50, y=4.09, z=43.50], EntityArmorStand['Armor Stand'/2338822, l='MpServer', x=3.50, y=94.41, z=-17.50], EntityArmorStand['Armor Stand'/2338821, l='MpServer', x=-2.50, y=99.03, z=-16.50], EntityArmorStand['Armor Stand'/2338820, l='MpServer', x=-2.50, y=99.41, z=-16.50], EntityPig['Pig'/2338571, l='MpServer', x=-3.56, y=100.00, z=-26.19], EntityPig['Pig'/2338570, l='MpServer', x=-4.84, y=100.00, z=-26.47], EntityArmorStand['§8[§7Lv4§8] §cSpider §a183§f/§a183§c?'/2339658, l='MpServer', x=51.50, y=3.19, z=42.50], EntityArmorStand['Armor Stand'/2338569, l='MpServer', x=-2.50, y=100.00, z=-25.50], EntitySpider['Spider'/2339657, l='MpServer', x=51.50, y=2.00, z=42.50], EntityArmorStand['Armor Stand'/2338568, l='MpServer', x=19.50, y=101.00, z=-22.50], EntityArmorStand['Armor Stand'/2338575, l='MpServer', x=-2.50, y=100.00, z=-16.50], EntityArmorStand['Armor Stand'/2338574, l='MpServer', x=3.50, y=100.00, z=36.50], EntityPig['Pig'/2338573, l='MpServer', x=-4.84, y=100.00, z=-25.03], EntityArmorStand['§8[§7Lv4§8] §cSpider §a183§f/§a183§c?'/2339661, l='MpServer', x=46.50, y=3.19, z=42.50], EntityPig['Pig'/2338572, l='MpServer', x=-1.31, y=100.00, z=-27.84], EntitySpider['Spider'/2339660, l='MpServer', x=46.50, y=2.00, z=42.50], EntityCow['Cow'/2338579, l='MpServer', x=-2.44, y=100.00, z=-17.81], EntityCow['Cow'/2338578, l='MpServer', x=-4.84, y=100.00, z=-16.50], EntityOtherPlayerMP['Mrendonuts'/2338650, l='MpServer', x=3.28, y=110.31, z=9.28], EntityCow['Cow'/2338577, l='MpServer', x=-0.16, y=100.00, z=-15.03], EntityCow['Cow'/2338576, l='MpServer', x=-3.31, y=100.00, z=-14.31], EntityArmorStand['Armor Stand'/2338581, l='MpServer', x=3.50, y=95.00, z=-17.50], EntityArmorStand['Armor Stand'/2338580, l='MpServer', x=20.50, y=101.00, z=-4.50], EntityArmorStand['§8[§7Lv4§8] §cSkeleton §a152§f/§a152§c?'/2339675, l='MpServer', x=52.50, y=4.00, z=18.50], EntityOtherPlayerMP['Mrendonuts'/2338650, l='MpServer', x=3.28, y=110.31, z=9.28], EntitySkeleton['Skeleton'/2339674, l='MpServer', x=52.50, y=2.00, z=18.50], EntityArmorStand['Armor Stand'/2341146, l='MpServer', x=19.50, y=100.03, z=-22.50], EntityArmorStand['Armor Stand'/2341145, l='MpServer', x=19.50, y=100.41, z=-22.50]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (Hypixel) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:402)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 363171264 bytes (346 MB) / 939524096 bytes (896 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_L5 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	skyblockaddons{1.5.2} [SkyBlock Addons] (SkyblockAddons-1.8.9-1.5.2.jar) 
	Loaded coremods (and transformers): 
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.8.9-1.5.2.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7926' Renderer: 'Intel(R) UHD Graphics 620'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 26.20.100.7926, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: 20191204-143016
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.7926
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

**System Information**
 - OS: [ Windows 10]
 - Mod Loader: [Forge Mod Loader]
 - Minecraft Version/Mod Loader Version: [e.g. 1.8.9 - 11.15.1.2318]
 - SkyblockAddons Version: [1.5.2]

**Comment by gbougard** [comment]
+1
Same issue, under win10 and even under linux (Fedora 31).

Just reproduced under linux with exactly the same stack trace (only few API line numbers are differents). Here is my detailed system informations from the error dump:
```
-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 5.7.11-100.fc31.x86_64
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor
	Java Version: 1.8.0_265, Red Hat, Inc
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Red Hat, Inc
	Memory: 513435536 bytes (489 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -Xms1G -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 Optifine OptiFine_1.8.9_HD_U_I3 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJA	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJA	skyblockaddons{1.5.2} [SkyBlock Addons] (SkyblockAddons-1.5.2-for-MC-1.8.9.jar) 
	Loaded coremods (and transformers): 
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.2-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
	GL info: ' Vendor: 'X.Org' Version: '4.5 (Compatibility Profile) Mesa 19.2.8' Renderer: 'AMD HAWAII (DRM 2.50.0, 5.7.11-100.fc31.x86_64, LLVM 9.0.1)'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1722
	LWJGL: 2.9.4
	OpenGL: AMD HAWAII (DRM 2.50.0, 5.7.11-100.fc31.x86_64, LLVM 9.0.1) GL version 4.5 (Compatibility Profile) Mesa 19.2.8, X.Org
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: v11F32x_Skyblock_Pack_1.8.9.zip
	Current Language: Français (France)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor
```
I tried here with `forge-1.8.9-11.15.1.1722.jar`, but it crashes also with `forge-1.8.9-11.15.1.2318-1.8.9.jar`

**Comment by gbougard** [comment]
[Looking at the code](https://github.com/BiscuitDevelopment/SkyblockAddons/blob/cf4930c75762e1f36948c0633d56c86a92f4d50c/src/main/java/codes/biscuit/skyblockaddons/listeners/RenderListener.java#L881) I found a work-around is to disable "Skill Progress Display" in SkyBlock Addons configuration. So skill progress displaying is broken when forging or enchanting.

**Comment by ILikePlayingGames** [comment]
We’re aware of this issue and it will be fixed in the next update. For now, please change your Hypixel language to English using `/lang English` as a workaround.

**Comment by gbougard** [comment]
Thanks for the tip, but there's an issue with inventory names when switching language as you can't stack stuffs with different names. As example, in french, "bones" are named "os". After switching the language, you can got 32 "os" and 32 "bones" but can't stack them into a 64 "bones". Is that also a known issue ?

**Comment by ILikePlayingGames** [comment]
The item names are controlled on Hypixel's side, I doubt we can do anything about that unfortunately.

**Comment by g-bougard** [comment]
I understand and thank you for the comment.

Anyway, if you have a PR for the current issue, I'm able to try it building the addon myself and validate the solution.

**Comment by ILikePlayingGames** [comment]
There's no PR for it, it should already be fixed. I forgot which commit it got fixed in.

**Comment by g-bougard** [comment]
Okay, I tried to build the development branch following the Contributors guide. For me (on linux, Fedora 31), the build fails on ":test" task. Finally I managed to make the build using `-x :test` option with gradlew. I still have a java.lang.NullPointerException during `:extractRangemapReplacedMain` task. I don't know if this is important and anyway it built `SkyblockAddons-1.6.0-beta.3-for-MC-1.8.9.jar`.

I tested it and I can confirm it fixes the issue. So this is issue is fixed for me in `development` branch.

**Comment by ILikePlayingGames** [comment]
The test failed because it doesn’t account for localization. I’ll have to fix that. The NullPointerException happens due to a problem in ForgeGradle or one of its libraries. It doesn’t seem to affect the build so we’ve been ignoring it. Thanks for confirming that it’s fixed!
